import type { Product } from "@/types"

const IMG = "/images/product.jpg"
const IMGS = ["/images/product1.jpg", "/images/product2.jpg"]

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Манты",
    weight: "1 кг",
    price: 740,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.8,
    content: "Фарш говяжий, соль, лук, перец, мука, вода",
    isNew: false,
    isHit: false,
    isPopular: true,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 2,
    name: "Манты по-домашнему",
    weight: "уточнить",
    price: 610,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 3,
    name: "Открытые манты",
    weight: "уточнить",
    price: 900,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 4,
    name: "Пельмени",
    weight: "1 кг",
    price: 670,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.8,
    content: "Фарш говяжий, лук, соль, перец, мука, вода, яйцо",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: true,
    tags: ["semi", "meat"],
  },
  {
    id: 5,
    name: "Пельмени куриные",
    weight: "уточнить",
    price: 580,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "chicken"],
  },
  {
    id: 6,
    name: "Мини пельмени",
    weight: "уточнить",
    price: 690,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 7,
    name: "Галушки",
    weight: "1 кг",
    price: 280,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.5,
    content: "Мука, вода, яйцо, соль",
    isNew: true,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 8,
    name: "Галушки с куркумой",
    weight: "1 кг",
    price: 280,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.5,
    content: "Мука, вода, яйцо, соль, куркума",
    isNew: false,
    isHit: true,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 9,
    name: "Галушки ушки",
    weight: "уточнить",
    price: 300,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.4,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 10,
    name: "Кукурузные галушки",
    weight: "1 кг",
    price: 390,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.5,
    content: "Кукурузная мука, соль, яйцо, растительное масло",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 11,
    name: "Вареники с творогом",
    weight: "1 кг",
    price: 520,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Творог, яйцо, соль, мука, вода",
    isNew: false,
    isHit: false,
    isPopular: true,
    isRecommended: false,
    tags: ["semi", "dessert"],
  },
  {
    id: 12,
    name: "Вареники с картошкой",
    weight: "1 кг",
    price: 410,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "Картошка, лук, соль, перец, мука, вода, яйцо, топлёное масло",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 13,
    name: "Бабушкины вареники с атарш",
    weight: "уточнить",
    price: 690,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 14,
    name: "Курзе",
    weight: "1 кг",
    price: 690,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Говяжий фарш, лук, соль, перец, чеснок, петрушка",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 15,
    name: "Казахские манты",
    weight: "8 шт",
    price: 570,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 16,
    name: "Хинкали с мясом",
    weight: "8 шт",
    price: 610,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.8,
    content: "Мука, яйцо, фарш говяжий, лук, соль, перец",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: true,
    tags: ["semi", "meat"],
  },
  {
    id: 17,
    name: "Хинкали с сыром",
    weight: "8 шт",
    price: 600,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Сулугуни, творог, мука, моцарелла, яйцо, вода, соль",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "cheese"],
  },
  {
    id: 18,
    name: "Чебуреки с мясом (полуфабрикаты)",
    weight: "5 шт",
    price: 590,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Фарш говяжий, лук, соль, перец, мука",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 19,
    name: "Чебуреки с сыром (полуфабрикаты)",
    weight: "5 шт",
    price: 550,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "cheese"],
  },
  {
    id: 20,
    name: "Куриные чебуреки (полуфабрикаты)",
    weight: "уточнить",
    price: 500,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "chicken"],
  },
  {
    id: 21,
    name: "Чебуреки с черемшой (полуфабрикаты)",
    weight: "уточнить",
    price: 650,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 22,
    name: "Мини чебуреки (полуфабрикаты)",
    weight: "10 шт",
    price: 750,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Фарш говяжий, лук, соль, перец, мука",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: true,
    tags: ["semi", "meat"],
  },
  {
    id: 23,
    name: "Мини чебуреки куриные (полуфабрикаты)",
    weight: "10 шт",
    price: 680,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "chicken"],
  },
  {
    id: 24,
    name: "Сырники классика",
    weight: "6 шт",
    price: 450,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "dessert"],
  },
  {
    id: 25,
    name: "Сырники с малиной",
    weight: "6 шт",
    price: 470,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Творог, сахар, малина, пшеничная мука, ванилин",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "dessert"],
  },
  {
    id: 26,
    name: "Сырники с маком",
    weight: "6 шт",
    price: 470,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Творог, мак, сахар, пшеничная мука, ванилин",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "dessert"],
  },
  {
    id: 27,
    name: "Сырники с цедрой апельсина",
    weight: "6 шт",
    price: 470,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Творог, сахар, цедра апельсина, пшеничная мука, ванилин",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "dessert"],
  },
  {
    id: 28,
    name: "Баарш",
    weight: "1 шт",
    price: 690,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 29,
    name: "Домашняя колбаса сушеная",
    weight: "1 кг",
    price: 1550,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["meat"],
  },
  {
    id: 30,
    name: "Йоьхьш",
    weight: "1 шт",
    price: 1450,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 31,
    name: "Мини баарш",
    weight: "2 шт",
    price: 1100,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 32,
    name: "Мини йоьхьш",
    weight: "2 шт",
    price: 850,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 33,
    name: "Котлеты куриные",
    weight: "6 шт",
    price: 650,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Фарш куриный, лук, топлёное масло, яйцо, специи",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "chicken"],
  },
  {
    id: 34,
    name: "Котлеты мясные",
    weight: "6 шт",
    price: 660,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Фарш говяжий, лук, соль, перец, яйцо, хлеб",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 35,
    name: "Котлеты по-киевски (полуфабрикаты)",
    weight: "4 шт",
    price: 700,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.8,
    content: "Куриное филе, хлеб, соль, перец, слив. масло, чеснок, сыр, укроп, сухари",
    isNew: false,
    isHit: false,
    isPopular: true,
    isRecommended: false,
    tags: ["semi", "chicken"],
  },
  {
    id: 36,
    name: "Фаршированные перцы",
    weight: "1 кг",
    price: 900,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Перец болгарский, лук, рис, фарш говяжий, соль, перец",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 37,
    name: "Голубцы (полуфабрикаты)",
    weight: "7 шт",
    price: 800,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.8,
    content: "Говяжий фарш, лук, рис, соль, перец, капуста",
    isNew: false,
    isHit: false,
    isPopular: true,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 38,
    name: "Тефтели",
    weight: "8 шт",
    price: 850,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Фарш говяжий, лук, рис, яйцо, соль, перец",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 39,
    name: "Фрикадельки говяжьи",
    weight: "500 г",
    price: 850,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "Фарш говяжий, лук, рис, яйцо, соль, перец",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 40,
    name: "Фрикадельки куриные",
    weight: "500 г",
    price: 790,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "Фарш куриный, лук, рис, яйцо, укроп, соль, перец",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "chicken"],
  },
  {
    id: 41,
    name: "Куриный люля кебаб",
    weight: "уточнить",
    price: 770,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "chicken"],
  },
  {
    id: 42,
    name: "Мясной люля кебаб",
    weight: "уточнить",
    price: 970,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 43,
    name: "Мясной рулет",
    weight: "уточнить",
    price: 2200,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 44,
    name: "Куриный рулет",
    weight: "уточнить",
    price: 2500,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "chicken"],
  },
  {
    id: 45,
    name: "Куриный мини рулет с овощной начинкой",
    weight: "2 шт",
    price: 900,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "chicken"],
  },
  {
    id: 46,
    name: "Куриный мини рулет с грибной начинкой",
    weight: "2 шт",
    price: 900,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "chicken"],
  },
  {
    id: 47,
    name: "Запеканка мини (на 2 порции)",
    weight: "уточнить",
    price: 790,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "Фарш говяжий, овощи, сыр, соль, перец, майонез",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 48,
    name: "Сискал с начинкой",
    weight: "1 шт",
    price: 410,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 49,
    name: "Ахьар межарг",
    weight: "6 шт",
    price: 390,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 50,
    name: "Ахьар тоьпш",
    weight: "14 шт",
    price: 390,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 51,
    name: "Мясо по-арабски (полуфабрикаты)",
    weight: "3 шт",
    price: 900,
    image: IMG,
    images: IMGS,
    shelfLife: "3 мес. при -18°C",
    category: "Полуфабрикаты",
    rating: 4.7,
    content: "Филе куриное, соль, перец, майонез, сыр, грецкий орех",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "chicken"],
  },
  {
    id: 52,
    name: "Стрипсы (полуфабрикаты)",
    weight: "уточнить",
    price: 750,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 53,
    name: "Зажарка",
    weight: "уточнить",
    price: 300,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.4,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 54,
    name: "Ханум рулет (полуфабрикаты)",
    weight: "уточнить",
    price: 650,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 55,
    name: "Блины",
    weight: "уточнить",
    price: 250,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.4,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 56,
    name: "Блины с мясом",
    weight: "уточнить",
    price: 450,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 57,
    name: "Блины с курицей",
    weight: "уточнить",
    price: 400,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "chicken"],
  },
  {
    id: 58,
    name: "Блины с творогом",
    weight: "уточнить",
    price: 300,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "dessert"],
  },
  {
    id: 59,
    name: "Кукурузный хинкал с мясом (полуфабрикаты)",
    weight: "уточнить",
    price: 910,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi", "meat"],
  },
  {
    id: 60,
    name: "Юьзан галнаш",
    weight: "1 кг",
    price: 1200,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },
  {
    id: 61,
    name: "Ахьар юьзан галнаш",
    weight: "1 кг",
    price: 1500,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Полуфабрикаты",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["semi"],
  },

  // =========================
  // Праздничные блюда
  // =========================
  {
    id: 62,
    name: "Шпинатный рулет",
    weight: "уточнить",
    price: 2200,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Праздничные блюда",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["holiday"],
  },
  {
    id: 63,
    name: "Баклажановые язычки",
    weight: "1 кг",
    price: 1100,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Праздничные блюда",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["holiday"],
  },
  {
    id: 64,
    name: "Баклажановые языки (премиум)",
    weight: "1 кг",
    price: 1500,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Праздничные блюда",
    rating: 4.8,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["holiday"],
  },
  {
    id: 65,
    name: "Куриный торт (вариант 1)",
    weight: "уточнить",
    price: 2200,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Праздничные блюда",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["holiday"],
  },
  {
    id: 66,
    name: "Куриный торт (вариант 2)",
    weight: "уточнить",
    price: 1500,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Праздничные блюда",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["holiday"],
  },
  {
    id: 67,
    name: "Куриный торт (вариант 3)",
    weight: "уточнить",
    price: 1200,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Праздничные блюда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["holiday"],
  },
  {
    id: 68,
    name: "Печеночный торт (вариант 1)",
    weight: "уточнить",
    price: 2200,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Праздничные блюда",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["holiday"],
  },
  {
    id: 69,
    name: "Печеночный торт (вариант 2)",
    weight: "уточнить",
    price: 1500,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Праздничные блюда",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["holiday"],
  },
  {
    id: 70,
    name: "Печеночный торт (вариант 3)",
    weight: "уточнить",
    price: 1200,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Праздничные блюда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["holiday"],
  },
  {
    id: 71,
    name: "Печеночные коржи",
    weight: "уточнить",
    price: 1500,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Праздничные блюда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["holiday"],
  },
  {
    id: 72,
    name: "Салат «Оливье»",
    weight: "1 кг",
    price: 1200,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Праздничные блюда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["holiday"],
  },

  // =========================
  // Мясная продукция
  // =========================
  {
    id: 73,
    name: "Стейки в маринаде",
    weight: "1 кг",
    price: 1200,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Мясная продукция",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["meat"],
  },
  {
    id: 74,
    name: "Курица в маринаде",
    weight: "уточнить",
    price: 1100,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Мясная продукция",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["chicken"],
  },
  {
    id: 75,
    name: "Курица разделанная",
    weight: "уточнить",
    price: 1000,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Мясная продукция",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["chicken"],
  },
  {
    id: 76,
    name: "Крылышки в маринаде",
    weight: "уточнить",
    price: 600,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Мясная продукция",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["chicken"],
  },
  {
    id: 77,
    name: "Куриное бедро в маринаде",
    weight: "уточнить",
    price: 600,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Мясная продукция",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["chicken"],
  },
  {
    id: 78,
    name: "Куриные ножки в маринаде",
    weight: "уточнить",
    price: 600,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Мясная продукция",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["chicken"],
  },

  // =========================
  // Рыба
  // =========================
  {
    id: 79,
    name: "Семга в маринаде",
    weight: "1 кг",
    price: 2400,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Рыба",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["fish"],
  },
  {
    id: 80,
    name: "Хек в маринаде",
    weight: "1 кг",
    price: 650,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Рыба",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["fish"],
  },

  // =========================
  // Готовая еда
  // =========================
  {
    id: 81,
    name: "Чебуреки с мясом (готовые)",
    weight: "1 шт",
    price: 120,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.7,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: true,
    isRecommended: false,
    tags: ["ready", "meat"],
  },
  {
    id: 82,
    name: "Чебуреки с сыром (готовые)",
    weight: "1 шт",
    price: 140,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready", "cheese"],
  },
  {
    id: 83,
    name: "Чебуреки с курицей (готовые)",
    weight: "1 шт",
    price: 110,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready", "chicken"],
  },
  {
    id: 84,
    name: "Мини чебуреки (готовые)",
    weight: "10 шт",
    price: 850,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 85,
    name: "Пирожки с картошкой",
    weight: "1 шт",
    price: 70,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 86,
    name: "Пирожки с капустой",
    weight: "1 шт",
    price: 70,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: true,
    tags: ["ready"],
  },
  {
    id: 87,
    name: "Пирожки с творогом",
    weight: "1 шт",
    price: 70,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready", "dessert"],
  },
  {
    id: 88,
    name: "Беляши",
    weight: "1 шт",
    price: 100,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 89,
    name: "Манты (порция)",
    weight: "1 порция",
    price: 300,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 90,
    name: "Пельмени (порция)",
    weight: "1 порция",
    price: 300,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 91,
    name: "Курзе (порция)",
    weight: "1 порция",
    price: 350,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 92,
    name: "Казахские манты (4 штуки)",
    weight: "4 шт",
    price: 350,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 93,
    name: "Вареники с творогом (порция)",
    weight: "1 порция",
    price: 250,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready", "dessert"],
  },
  {
    id: 94,
    name: "Вареники с картошкой (порция)",
    weight: "1 порция",
    price: 200,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 95,
    name: "Запеканка (на 2 порции)",
    weight: "2 порции",
    price: 800,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 96,
    name: "Ханум",
    weight: "уточнить",
    price: 650,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 97,
    name: "Мясо по-арабски (готовое)",
    weight: "1 шт",
    price: 350,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 98,
    name: "Котлеты по-киевски (готовые)",
    weight: "1 шт",
    price: 200,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 99,
    name: "Сырники (готовые)",
    weight: "уточнить",
    price: 370,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.6,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready", "dessert"],
  },
  {
    id: 100,
    name: "Куриная котлета (готовая)",
    weight: "1 шт",
    price: 130,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready", "chicken"],
  },
  {
    id: 101,
    name: "Говяжие котлеты (готовые)",
    weight: "1 шт",
    price: 150,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready", "meat"],
  },
  {
    id: 102,
    name: "Ахьар тоьпш (готовое)",
    weight: "1 шт",
    price: 40,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.4,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 103,
    name: "Ахьар межарг (готовое)",
    weight: "1 шт",
    price: 90,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.4,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 104,
    name: "Сискал с начинкой (готовое)",
    weight: "1 шт",
    price: 100,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.4,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 105,
    name: "Юьзан галнаш (готовое)",
    weight: "6 шт",
    price: 700,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 106,
    name: "Ахьар юьзан галнаш (готовое)",
    weight: "5 шт",
    price: 800,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 107,
    name: "Самса",
    weight: "1 шт",
    price: 120,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 108,
    name: "Кукурузный хинкал с мясом (готовое)",
    weight: "5 шт",
    price: 370,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 109,
    name: "Черемша (не жареная)",
    weight: "1 кг",
    price: 1200,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.5,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 110,
    name: "Соленая капуста",
    weight: "2 л",
    price: 390,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.4,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },
  {
    id: 111,
    name: "Квашеная капуста",
    weight: "1 л",
    price: 410,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Готовая еда",
    rating: 4.4,
    content: "уточнить",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["ready"],
  },

  // =========================
  // Заготовки
  // =========================
  {
    id: 112,
    name: "Варенье из малины",
    weight: "уточнить",
    price: 350,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Заготовки",
    rating: 4.6,
    content: "Малина, сахар",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: true,
    tags: ["jam"],
  },
  {
    id: 113,
    name: "Варенье айвы",
    weight: "уточнить",
    price: 550,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Заготовки",
    rating: 4.5,
    content: "Айва, сахар",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["jam"],
  },
  {
    id: 114,
    name: "Облепиховое варенье",
    weight: "уточнить",
    price: 500,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Заготовки",
    rating: 4.5,
    content: "Облепиха, сахар",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["jam"],
  },
  {
    id: 115,
    name: "Перетертая малина",
    weight: "уточнить",
    price: 250,
    image: IMG,
    images: IMGS,
    shelfLife: "уточнить",
    category: "Заготовки",
    rating: 4.5,
    content: "Малина",
    isNew: false,
    isHit: false,
    isPopular: false,
    isRecommended: false,
    tags: ["jam"],
  },
]

export const popularProducts = PRODUCTS.filter((p) => p.isPopular)
export const recommendedProducts = PRODUCTS.filter((p) => p.isRecommended)
export const hitProducts = PRODUCTS.filter((p) => p.isHit)
export const newProducts = PRODUCTS.filter((p) => p.isNew)